fix(disk_encryption): make sure encryption pw change at firstboot works again

diff --git a/tasks/03_luks.yml b/tasks/03_luks.yml
--- a/tasks/03_luks.yml
+++ b/tasks/03_luks.yml
@@ -5,11 +5,11 @@
   register: potos_firstboot_is_crypt
   changed_when: false
 
-- name: Ask new disk encryption password
+- name: Change disk encryption password
   ansible.builtin.shell:
     executable: '/bin/bash'
     cmd: |
-      while [ ${POTOS_NEW_LUKS_PW} != ${POTOS_NEW_LUKS_PW2} -o -z ${POTOS_NEW_LUKS_PW2} ]; do
+      while ([ ${POTOS_NEW_LUKS_PW} != ${POTOS_NEW_LUKS_PW2} ] || [ -z ${POTOS_NEW_LUKS_PW2} ] || [ -z ${POTOS_OLD_LUKS_PW_TEST} ]); do
         USERINPUT="$(yad --fullscreen --title '{{ potos_firstboot_client_name }} Setup' \
           --borders 20 --align center \
           --button gtk-ok \
@@ -23,50 +23,49 @@
       Please enter your new disk encryption password below
       " \
           --form \
-          --field 'Password:H' \
-          --field 'Confirm password:H'
+          --field 'Current disk encryption password:H' \
+          --field 'New disk encryption password:H' \
+          --field 'Confirm new disk encryption password:H'
         )"
 
-        POTOS_NEW_LUKS_PW="$(echo ${USERINPUT} | cut -d '|' -f 1)"
-        POTOS_NEW_LUKS_PW2="$(echo ${USERINPUT} | cut -d '|' -f 2)"
+        #Save UserInput
+        POTOS_OLD_LUKS_PW="$(echo ${USERINPUT} | cut -d '|' -f 1)"
+        POTOS_NEW_LUKS_PW="$(echo ${USERINPUT} | cut -d '|' -f 2)"
+        POTOS_NEW_LUKS_PW2="$(echo ${USERINPUT} | cut -d '|' -f 3)"
 
-        if [[ -z ${POTOS_NEW_LUKS_PW} || -z ${POTOS_NEW_LUKS_PW2} ]]; then
+        #Test POTOS_OLD_LUKS_PW if the given Password is correct.
+          eval "$(awk '/crypt/ {print $2}' /etc/crypttab)" && LUKS_DEVICE="$(realpath "/dev/disk/by-uuid/${UUID}")"
+          printf "${POTOS_OLD_LUKS_PW}" | sudo cryptsetup luksOpen --test-passphrase $LUKS_DEVICE
+        if [ $? -eq 0 ]; then
+          POTOS_OLD_LUKS_PW_TEST="correct"
+        fi
+
+        if [ -z ${POTOS_OLD_LUKS_PW_TEST} ]; then
+          yad --title "{{ potos_firstboot_client_name }} Setup" \
+            --borders 20 --align center --button gtk-ok --image-on-top \
+            --image=/setup/logo.png \
+            --text 'The given old disk encryption password was incorrect. Please try again.'
+        fi
+
+        if [ -z ${POTOS_NEW_LUKS_PW} ] || [ -z ${POTOS_NEW_LUKS_PW2} ]; then
           yad --title "{{ potos_firstboot_client_name }} Setup" \
             --borders 20 --align center --button gtk-ok --image-on-top \
             --image=/setup/logo.png \
             --text 'Please choose and enter your new credentials.'
         fi
-        if [[  ${POTOS_NEW_LUKS_PW} != ${POTOS_NEW_LUKS_PW2} ]]; then
+        if [  ${POTOS_NEW_LUKS_PW} != ${POTOS_NEW_LUKS_PW2} ]; then
           yad --title "{{ potos_firstboot_client_name }} Setup" \
             --borders 20 --align center --button gtk-ok --image-on-top \
             --image=/setup/logo.png \
             --text 'Your password was not identical. Please try again.'
         fi
       done
-      echo $POTOS_NEW_LUKS_PW
-  register: potos_new_luks_password
-  when:
-    - potos_firstboot_ask_change_disk_enc_pw
-    - potos_firstboot_is_crypt.stdout != '0'
-  tags:
-    - 'molecule-notest'
 
-- name: Print old luks pw from env
-  ansible.builtin.shell: . /setup/.env && echo ${POTOS_DISK_ENCRYPTION_INITIAL_PASSWORD}
-  register: potos_old_luks_password
-  when:
-    - potos_firstboot_ask_change_disk_enc_pw
-    - potos_firstboot_is_crypt.stdout != '0'
-  changed_when: false
-
-- name: Change boot disk encryption luks password now
-  ansible.builtin.shell:
-    executable: '/bin/bash'
-    cmd: |
+      #Change disk encryption password now
       eval "$(awk '/crypt/ {print $2}' /etc/crypttab)" && LUKS_DEVICE="$(realpath "/dev/disk/by-uuid/${UUID}")"
-      printf '%s\n' '{{ potos_old_luks_password.stdout }}' "{{ potos_new_luks_password.stdout }}" | cryptsetup luksChangeKey "${LUKS_DEVICE}" -q
+      printf '%s\n' "${POTOS_OLD_LUKS_PW}" "${POTOS_NEW_LUKS_PW}" | cryptsetup luksChangeKey "${LUKS_DEVICE}" -q
       if [[ $? -ne 0 ]]; then
-        echo "# Failed to change primary disk encryption key"
+        echo "# Failed to change primary disk encryption key."
         exit 1
       fi
   when:
